name: workflow overview

on: 
  workflow_dispatch:

jobs:
a_simple_jobs: my simple job name
runs-on: ubuntu-latest
steps:
- name of my step
run: echo "This is the first step from first job"
- name: step with another shell
id: shellStep
shell: python
run: print("This step is using the python shell")
