name: Workflow Overview

on:
  workflow_dispatch:

jobs:
  a_simple_job:          # Job ID (no spaces)
    name: My Simple Job Name
    runs-on: ubuntu-latest

    steps:
      - name: My First Step
        run: echo "This is the first step from first job"

      - name: Step with another shell
        id: shellStep
        shell: python
        run: print("This step is using the python shell")
